### ISSUE TITLE
flash  with j-link lite

### ISSUE THREAD

**Issue by arteck** [antst/CC2538ZNP#1]
which Device is it 
![grafik](https://user-images.githubusercontent.com/6681528/62007998-b85d4400-b154-11e9-8e39-5bb7ae66810c.png)

**Comment by antst** [comment]
Depend on what module you have :)
If you have the same as mine, then SF53

**Comment by arteck** [comment]
ok flash done... THX

**Comment by antst** [comment]
I have heard that you have some issues. Please, can you elaborate?
But, at first, try updated firmware.

**Comment by arteck** [comment]
I'll contact you
