### ISSUE TITLE
Possibility to build a CC2538-stick (with external antenna) for me as well? 

### ISSUE THREAD

**Issue by imdos** [antst/CC2538ZNP#4]
Hi Anton, 

I saw your [post here](https://github.com/Koenkk/zigbee2mqtt/issues/1568#issuecomment-519661790) and am interested in one. My soldering skills aren't that great and certainly not at SMD level. Furthermore I don't have the BOM etc. Therefore I would like to purchase one from you if possible. 

Thanks in advance.

**Comment by antst** [comment]
Unfortunately, this is not possible. I don't have neither final PCBs nor spare modules.
But I suggest to try to team-up with someone in Z2M discord. Anybody who will order PCBs. will order at least 5 of them, so you can ask if someone can help you.

**Comment by egony** [comment]
Hi @imdos!
I can build this stick for you. But I have no idea about the international postage of the stick and international payment. I am territorially in Russia and have never exchanged with other countries.

**Comment by imdos** [comment]
Hi @egony,

Please drop me a line at imdos@protonmail.com and we can try to arrange something. Thanks

**Comment by egony** [comment]
Hi @imdos!
I sent mail, but take no answer. Maybe protonmail blocked in Russia :/

**Comment by imdos** [comment]
I fixed it myself some 4 years ago
