### ISSUE TITLE
Compare with CC2530

### ISSUE THREAD

**Issue by SchumyHao** [antst/CC2538ZNP#5]
If CC2530 with source routing function can connect 5 EPs directly, What about CC2538?
Do I need re-join all devices after I change my original cc2530 with source routing?
How many EPs can connect to CC2538 with current firmware?
Does current firmware support source routing?

Thank you for your work.
Wish to get your reply

**Comment by imdos** [comment]
Hi @SchumyHao if I recall it correctly; 40 devices shouldn't be a problem for CC2538. Have a look at [this post](https://github.com/Koenkk/zigbee2mqtt/issues/1568#issuecomment-543741460) as well. AFAIK Z3.0 has another type of network setup and already supports source routing, but the CC2530/1 is not capable of supporting it according to Koenkk. I have read that in one of the 3 linked threads. 

You need to rejooin all devices when changing from Z1.2 to Z3.0 and from device to device. See [this post](https://github.com/Koenkk/zigbee2mqtt/issues/1445#issuecomment-536483670). 

Koenkk is working on support for another board (CC2652R/CC1352P-2) as well. You can follow the progress [here](https://github.com/Koenkk/zigbee2mqtt/issues/1429).

**Comment by SchumyHao** [comment]
Thank you very much @imdos .
I'll follow those post
